name: YScript
description: YEAHx4 Script Plugin
version: 1.0.0-alpha
author: YEAHx4
main: com.github.yeahx4.JavaMain

commands:
  scriptlist:
    usage: "/scriptlist"
    description: "get list of script"
    permission-message: "Access denied (Permission rejected)"
    aliases: ["스크립트목록", "sl"]
